// <auto-generated />
namespace HalloDal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201310051638336_Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
